// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPrototype.Models;

namespace ProjectPrototype.Migrations.Player
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20220410222602_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectPrototype.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumAtBats")
                        .HasColumnType("int");

                    b.Property<int>("NumEarnedRunsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("NumErrors")
                        .HasColumnType("int");

                    b.Property<int>("NumHits")
                        .HasColumnType("int");

                    b.Property<int>("NumHittingStrikeouts")
                        .HasColumnType("int");

                    b.Property<int>("NumHomeruns")
                        .HasColumnType("int");

                    b.Property<int>("NumHomerunsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("NumInningsPitched")
                        .HasColumnType("int");

                    b.Property<int>("NumPitchingStrikeouts")
                        .HasColumnType("int");

                    b.Property<int>("NumPlays")
                        .HasColumnType("int");

                    b.Property<int>("NumRBI")
                        .HasColumnType("int");

                    b.Property<int>("NumWalks")
                        .HasColumnType("int");

                    b.Property<int>("NumWalksAllowed")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            DOB = new DateTime(2013, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Max",
                            Height = 49,
                            LastName = "Smith",
                            NumAtBats = 0,
                            NumEarnedRunsAllowed = 0,
                            NumErrors = 0,
                            NumHits = 0,
                            NumHittingStrikeouts = 0,
                            NumHomeruns = 0,
                            NumHomerunsAllowed = 0,
                            NumInningsPitched = 0,
                            NumPitchingStrikeouts = 0,
                            NumPlays = 0,
                            NumRBI = 0,
                            NumWalks = 0,
                            NumWalksAllowed = 0,
                            Position = "C",
                            TeamId = 1,
                            Weight = 65
                        },
                        new
                        {
                            PlayerId = 2,
                            DOB = new DateTime(2013, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jackson",
                            Height = 57,
                            LastName = "Frome",
                            NumAtBats = 0,
                            NumEarnedRunsAllowed = 0,
                            NumErrors = 0,
                            NumHits = 0,
                            NumHittingStrikeouts = 0,
                            NumHomeruns = 0,
                            NumHomerunsAllowed = 0,
                            NumInningsPitched = 0,
                            NumPitchingStrikeouts = 0,
                            NumPlays = 0,
                            NumRBI = 0,
                            NumWalks = 0,
                            NumWalksAllowed = 0,
                            Position = "RF",
                            TeamId = 2,
                            Weight = 91
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
