// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectPrototype.Models;

namespace ProjectPrototype.Migrations
{
    [DbContext(typeof(RosterContext))]
    partial class RosterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectPrototype.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            DateTime = new DateTime(2022, 4, 10, 2, 30, 0, 0, DateTimeKind.Unspecified),
                            Location = "College Station, TX"
                        });
                });

            modelBuilder.Entity("ProjectPrototype.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Manager");

                    b.HasData(
                        new
                        {
                            ManagerId = 1,
                            Email = "mstevens@verizon.net",
                            FirstName = "Mike",
                            LastName = "Stevens",
                            Phone = 9723389204L,
                            TeamId = 1
                        },
                        new
                        {
                            ManagerId = 2,
                            Email = "freemansports@gmail.com",
                            FirstName = "John",
                            LastName = "Freeman",
                            Phone = 9725478392L,
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("ProjectPrototype.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            MatchId = 1,
                            GameId = 1,
                            Outcome = 1,
                            Score = 2,
                            TeamId = 1
                        },
                        new
                        {
                            MatchId = 2,
                            GameId = 1,
                            Outcome = 0,
                            Score = 12,
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("ProjectPrototype.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumAtBats")
                        .HasColumnType("int");

                    b.Property<int>("NumEarnedRunsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("NumErrors")
                        .HasColumnType("int");

                    b.Property<int>("NumHits")
                        .HasColumnType("int");

                    b.Property<int>("NumHittingStrikeouts")
                        .HasColumnType("int");

                    b.Property<int>("NumHomeruns")
                        .HasColumnType("int");

                    b.Property<int>("NumHomerunsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("NumInningsPitched")
                        .HasColumnType("int");

                    b.Property<int>("NumPitchingStrikeouts")
                        .HasColumnType("int");

                    b.Property<int>("NumPlays")
                        .HasColumnType("int");

                    b.Property<int>("NumRBI")
                        .HasColumnType("int");

                    b.Property<int>("NumWalks")
                        .HasColumnType("int");

                    b.Property<int>("NumWalksAllowed")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            DOB = new DateTime(2013, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Max",
                            Height = 49,
                            LastName = "Smith",
                            NumAtBats = 0,
                            NumEarnedRunsAllowed = 0,
                            NumErrors = 0,
                            NumHits = 0,
                            NumHittingStrikeouts = 0,
                            NumHomeruns = 0,
                            NumHomerunsAllowed = 0,
                            NumInningsPitched = 0,
                            NumPitchingStrikeouts = 0,
                            NumPlays = 0,
                            NumRBI = 0,
                            NumWalks = 0,
                            NumWalksAllowed = 0,
                            Position = "C",
                            TeamId = 1,
                            Weight = 65
                        },
                        new
                        {
                            PlayerId = 2,
                            DOB = new DateTime(2013, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jackson",
                            Height = 57,
                            LastName = "Frome",
                            NumAtBats = 0,
                            NumEarnedRunsAllowed = 0,
                            NumErrors = 0,
                            NumHits = 0,
                            NumHittingStrikeouts = 0,
                            NumHomeruns = 0,
                            NumHomerunsAllowed = 0,
                            NumInningsPitched = 0,
                            NumPitchingStrikeouts = 0,
                            NumPlays = 0,
                            NumRBI = 0,
                            NumWalks = 0,
                            NumWalksAllowed = 0,
                            Position = "RF",
                            TeamId = 2,
                            Weight = 91
                        });
                });

            modelBuilder.Entity("ProjectPrototype.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Mascot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Losses = 0,
                            Mascot = "Horse",
                            TeamName = "Roughriders",
                            Wins = 0
                        },
                        new
                        {
                            TeamId = 2,
                            Losses = 0,
                            Mascot = "Hammerhead",
                            TeamName = "Sharks",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("ProjectPrototype.Models.Manager", b =>
                {
                    b.HasOne("ProjectPrototype.Models.Team", "Team")
                        .WithMany("Managers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectPrototype.Models.Match", b =>
                {
                    b.HasOne("ProjectPrototype.Models.Game", "Game")
                        .WithMany("Matches")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectPrototype.Models.Team", "Team")
                        .WithMany("Matches")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectPrototype.Models.Player", b =>
                {
                    b.HasOne("ProjectPrototype.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
